(source melpa)

(depends-on "ag")
(depends-on "aggressive-indent")
(depends-on "auto-complete")
(depends-on "autopair")
(depends-on "color-theme-solarized")
(depends-on "enh-ruby-mode")
(depends-on "pallet")
(depends-on "powerline")
(depends-on "ruby-end")
(depends-on "smartparens")
(depends-on "soft-morning-theme")
(depends-on "solarized-theme")